name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  imports:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run import boundary checks (non-strict)
        run: bash scripts/check_imports.sh

  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `run` step
        run: zig build run

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `test` step
        run: zig build test --summary all

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `fmt` step
        run: zig build fmt

  # Enable strict mode by setting env CI_STRICT_IMPORTS=1 at workflow or job level
  # once violations are resolved.
