name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  imports:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run import boundary checks (non-strict)
        run: bash scripts/check_imports.sh

  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `run` step
        run: zig build run

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `test` step
        run: zig build test --summary all

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `fmt` step
        run: zig build fmt

  agents:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: List agents
        run: zig build list-agents

      - name: Validate agents
        run: zig build validate-agents

      - name: Test AMP agent
        run: zig build -Dagent=amp test

      - name: Test markdown agent
        run: zig build -Dagent=markdown test

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Build AMP agent (release-safe)
        run: zig build -Dagent=amp --release=safe

      - name: Build markdown agent (release-safe)
        run: zig build -Dagent=markdown --release=safe

  # Enable strict mode by setting env CI_STRICT_IMPORTS=1 at workflow or job level
  # once violations are resolved.
