name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Set up minisign
        run: |
          curl -L https://github.com/jedisct1/minisign/releases/latest/download/minisign-0.12-linux.tar.gz -o minisign.tar.gz
          tar -xf minisign.tar.gz
          echo "$GITHUB_WORKSPACE/minisign-linux/x86_64/" >> $GITHUB_PATH

      - name: Run `release` step
        run: zig build release

      - name: Sign release binaries
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
          MINISIGN_PUBLIC_KEY: ${{ secrets.MINISIGN_PUBLIC_KEY }}
        run: |
          echo "$MINISIGN_SECRET_KEY" > minisign.key
          minisign -S -s minisign.key -m zig-out/release/*
          echo "$MINISIGN_PUBLIC_KEY" > zig-out/release/minisign.pub
          rm minisign.key

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/release/*
          body: |
            Archived binary files can be verified as follows:
            ```sh
            minisign -Vm <archive> -p minisign.pub
            ```
          generate_release_notes: true
